name: Fix Issue
description: Add a fix issue
title: '[Fix]: '
labels: ['bug']
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: issue-detail
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: '- '
    validations:
      required: true
